### PR TITLE
react 16 fixes

### PR DESCRIPTION
**Pull request by orouz**
after upgrading to react 16 i got a bunch of errors (mostly undefineds), fixed it! :) 

i'm using `prettier` and it kinda changed the entire file so it's harder to see what actually changed. 

so here's what changed:

1 - added a check to see if we have the refs yet 
2 - changed some wrong name variables (`positions`)

that's pretty much it i think. 

i'm using this in one of my projects and i really like it! let me know if you need anything else to merge this, i prefer not keeping a fork.

### CODE REVIEW

**Review by radekmie — CHANGES_REQUESTED** [review]
Could you split this into 2 PRs? I'm OK with prettier, but it's not a good practice to change whole project for a simple fix.

**Comment by radekmie** [comment]
And for the prettier PR (if you are willing to do it):
* 4 spaces
* single quotes
* configure it in the project

**Comment by orouz** [comment]
yeah i should split it 
can you share a prettier config file?

**Comment by radekmie** [comment]
I’d go with this one: https://github.com/vazco/eslint-config-vazco.

**Pull request closed without merging**
